### ISSUE TITLE
MetaWeather does not have open CORS

### ISSUE THREAD

**Issue by Nektro** [toddmotto/public-apis#644]

**Comment by davemachado** [comment]
Hi @Nektro , do you have some way of showing that MetaWeather does not support CORS? Thanks.

**Comment by Nektro** [comment]
When loading https://www.metaweather.com/api/location/2487956/ the API does not attach the response header `Access-Control-Allow-Origin: *` which is required by browsers for websites outside the domain `metaweather.com` from requesting its content.

![image](https://user-images.githubusercontent.com/5464072/38593306-bedf2642-3d0e-11e8-9adb-2c2fb93e9562.png)

**Comment by davemachado** [comment]
Great, thanks. Fixed in 8d3c175f8f0e80fd27b66430685c9418cf36071e

**Comment by Fronesis** [comment]
![image](https://user-images.githubusercontent.com/27814608/71086946-55b82380-219b-11ea-9613-deb4f57372b6.png)

**Comment by dungnguyent8** [comment]
I guess it's still not fixed!
![image](https://user-images.githubusercontent.com/39462756/97795149-4025de00-1c35-11eb-9d6d-8d8767d72e2c.png)

**Comment by yannbertrand** [comment]
Alright, I'm removing MetaWeather from the list. Thanks for the alert.

**Comment by gmxtrra** [comment]
USE THIS EXTENTION TO REMOVE THE APIs CORS ERROR

`https://add0n.com/access-control.html?version=0.1.9&type=install`
